### ISSUE TITLE
[Bug]: スマホビューでのメニューを追加

### ISSUE THREAD

**Issue by mantaroh** [unimal-jp/spear-doc#10]
### 📝 Issue Description / 問題の説明

現在、スマートフォンで表示するとメインメニューが隠れてしまっているので、メニュー(できればハンバーガーで開くやつ)にしたい

### 📋 On which page(s) it occurs / 問題のあるページ

N/A

### 🤔 Expected Behavior / 期待結果

N/A

### 👀 Current Behavior / 現在の動き

N/A

### 🖥️ Browser / ブラウザ

N/A

**Comment by capibaraya** [comment]
It's testing for comment(Instead of mantaroh account)

**Comment by June202325** [comment]
@mantaroh 
この課題を担当させていただきたいです！

**Comment by mantaroh** [comment]
https://stackblitz.com/github/unimal-jp/spear-doc

ここにアクセスしてください。

1.  画面真ん中下にコマンドが打てる箇所があります。そこで以下のコマンドを実行してください。
    1.  npm install
     2. npm run dev-jp
2.  画面右に修正後のページが表示されます。
3.  @June202325  さんの修正したファイルを試しにこの StackBlitz 上で編集して、修正が正しく動いているかを確認してください

**Comment by mantaroh** [comment]
@June202325 

修正したコードがちゃんと動くことを確認したら、 `git clone` でローカルに落としたディレクトリから修正を正式ページに反映させるため、プルリク(PullRequest)を作っていただきたいです。

以下のページの解説にある PullRequest の出し方を参考にしながら修正を PullRequest にしてみてください。
https://qiita.com/aipacommander/items/d61d21988a36a4d0e58b#4%E4%BF%AE%E6%AD%A3%E3%82%92%E5%8A%A0%E3%81%88%E3%82%8B%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88
(手順４の修正を加えるパートは、自身の修正になるのでスキップして良いです)

ソフトウェアの開発では、この手順をよく使って、これからの課題でも利用します。

わからないことがあれば、随時質問してください。

**Comment by June202325** [comment]
お疲れ様です。
ハンバーガーメニューの追加の仕方が調べても分からなかったので、教えていただけますでしょうか。
よろしくお願いいたします。

**Comment by mantaroh** [comment]
この Issue は少し難しいかもです。
簡単なサンプルを作ってみました。
https://codepen.io/mantaroh/pen/oNmJvZm

ハンバーガーメニューは、ボタンを押したときに CSS のクラスを追加することで実現します。
以下の解説ページがわかりやすいかと思いますので、一回読んで下さい。

https://global-web-design.com/1093/

また、今回の修正は難しいので、修正するプログラムを書いてみました。
https://github.com/unimal-jp/spear-doc/compare/main...fix/humberger-menu

↑のアドレスを見ると変更すべきファイルがわかります（ `yarn.lock` だけは関係のないファイルですので、無視して下さい)

**Comment by June202325** [comment]
承知いたしました。
ありがとうございます！

**Comment by mantaroh** [comment]
初めての貢献ありがとうございます！
内容問題ありませんでした！
