### ISSUE TITLE
[Bug]: 画面別にコンテンツ幅を広げる

### ISSUE THREAD

**Issue by mantaroh** [unimal-jp/spear-doc#16]
### 📝 Issue Description / 問題の説明

PC で開いてもコンテンツの幅が 500px になっているため、閲覧しにくい原因の1つになっている

### 📋 On which page(s) it occurs / 問題のあるページ

全ページ

### 🤔 Expected Behavior / 期待結果

PC・スマホ・タブレット別に以下の幅になっていること

| タイプ | タイプの区別方法 | 幅 |
| - | - | - |
| PC | 画面幅が 1280px 以上 | 900px |
| タブレット | 画面幅が 768px~1279px | 700 px |
| スマホ | 画面幅が 768px 以下 | 480px |

### 👀 Current Behavior / 現在の動き

常に500px になっている

### 🖥️ Browser / ブラウザ

N/A

### 📄 Additional Information

N/A

**Comment by 0000okmn** [comment]
担当したいです！！よろしくお願いします！！

**Comment by 0000okmn** [comment]
@mantaroh 担当したいです！！よろしくお願いします！！

**Comment by mantaroh** [comment]
この修正は、最初に以下の修正をしてみて下さい。

https://github.com/unimal-jp/spear-doc/blob/main/src/assets/css/main.scss#L21

この箇所に書いている
```
width: 500px;
```

を

```
width: 900px;
```

に変更します。
変更後、StackBlitz で画面を確認してみて下さい。

**Comment by mantaroh** [comment]
@0000okmn 

貢献ありがとうございます！
修正内容も問題なくバッチシでした！
