### ISSUE TITLE
[Bug]: マークダウン紹介ページのサンプルコードのタイポ

### ISSUE THREAD

**Issue by mantaroh** [unimal-jp/spear-doc#7]
### 📝 Issue Description / 問題の説明

以下の定義の間違い

```
import { markdownPlugin } from "@spearly/spear-markdown-plugin";

export default {
  ...
  "plugins": [
    markdowmarkdownPluginnPlugin(),
  ]
}
```

`markdowmarkdownPluginnPlugin` -> `markdownPlugin `

### 📋 On which page(s) it occurs / 問題のあるページ

- /en/basic/markdown.html
- /jp/basic/markdown.html

### 🤔 Expected Behavior / 期待結果

```
import { markdownPlugin } from "@spearly/spear-markdown-plugin";

export default {
  ...
  "plugins": [
    markdownPlugin (),
  ]
}
```

### 👀 Current Behavior / 現在の動き

間違ったコードがそのまま記載されている。

### 🖥️ Browser / ブラウザ

https://www.whatsmybrowser.org/b/Z6O07

**Comment by K-Yuma** [comment]
@mantaroh このIssueを担当したいです！

**Comment by mantaroh** [comment]
@K-Yuma 

貢献ありがとうございます〜！
めっちゃいい感じで早い修正でした！

この Issue は対応済みのため、クローズします
